import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { X, ChevronRight, CloudUpload, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { insertCourseSchema } from "@shared/schema";
import { z } from "zod";

const courseSetupSchema = z.object({
  topic: z.string().min(1, "Course topic is required"),
  targetAudience: z.string().min(1, "Target audience is required"),
  learningObjectives: z.string().min(1, "Learning objectives are required"),
  duration: z.string().optional(),
  difficulty: z.string().optional(),
  status: z.string().default("draft"),
  referenceUrls: z.array(z.string()).optional(),
  files: z.array(z.instanceof(File)).optional(),
});

type CourseSetupForm = z.infer<typeof courseSetupSchema>;

export default function CourseSetup() {
  const [, setLocation] = useLocation();
  const [creationMode, setCreationMode] = useState<"ai" | "upload">("ai");
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [referenceUrls, setReferenceUrls] = useState<string[]>([""]);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const { toast } = useToast();

  const form = useForm<CourseSetupForm>({
    resolver: zodResolver(courseSetupSchema),
    defaultValues: {
      topic: "",
      targetAudience: "",
      learningObjectives: "",
      duration: "3-5 hours",
      difficulty: "Beginner",
      status: "draft",
    },
  });

  const createCourseMutation = useMutation({
    mutationFn: async (data: CourseSetupForm) => {
      const courseData = {
        ...data,
        title: data.topic,
        referenceUrls: referenceUrls.filter(url => url.trim() !== ""),
      };
      
      // Step 1: Create the course
      const courseResponse = await apiRequest("POST", "/api/courses", courseData);
      const course = await courseResponse.json();
      
      // Step 2: Upload files if any
      if (selectedFiles.length > 0) {
        const formData = new FormData();
        selectedFiles.forEach(file => formData.append('files', file));
        
        try {
          await apiRequest("POST", `/api/courses/${course.id}/upload`, formData);
        } catch (error) {
          // File upload failed but continue with course creation
        }
      }
      
      // Step 3: Generate course outline automatically
      await apiRequest("POST", `/api/courses/${course.id}/generate-outline`);
      
      // Step 4: Generate cover image automatically
      try {
        await apiRequest("POST", `/api/courses/${course.id}/generate-cover-image`);
      } catch (error) {
        // Cover image generation failed but don't fail the whole course creation
        console.warn('Cover image generation failed:', error);
      }
      
      return course;
    },
    onSuccess: (course) => {
      toast({
        title: "Success",
        description: "Course created and outline generated successfully!",
      });
      setLocation(`/my-courses`);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "Failed to create course and generate outline. Please try again.",
        variant: "destructive",
      });
    },
  });

  const createCourseFromUploadMutation = useMutation({
    mutationFn: async () => {
      if (selectedFiles.length === 0) {
        throw new Error("Upload at least one file.");
      }

      const courseData = {
        title: "Uploaded Document Course",
        topic: "Generate this course from the uploaded document",
        targetAudience: "Generated by AI from uploaded source material.",
        learningObjectives: "Generate course title, course objectives, module learning objectives, and chapter outline from the uploaded document.",
        status: "draft",
      };

      const courseResponse = await apiRequest("POST", "/api/courses", courseData);
      const course = await courseResponse.json();

      const formData = new FormData();
      selectedFiles.forEach((file) => formData.append("files", file));
      await apiRequest("POST", `/api/courses/${course.id}/upload`, formData);
      await apiRequest("POST", `/api/courses/${course.id}/generate-outline-from-files`);

      try {
        await apiRequest("POST", `/api/courses/${course.id}/generate-cover-image`);
      } catch (error) {
        console.warn("Cover image generation failed:", error);
      }

      return course;
    },
    onSuccess: () => {
      toast({
        title: "Success",
        description: "Course created from uploaded document successfully!",
      });
      setLocation(`/my-courses`);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to create course from uploaded document.",
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: CourseSetupForm) => {
    createCourseMutation.mutate(data);
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    setSelectedFiles(prev => [...prev, ...files]);
  };

  const removeFile = (index: number) => {
    setSelectedFiles(prev => prev.filter((_, i) => i !== index));
  };

  const addReferenceUrl = () => {
    setReferenceUrls(prev => [...prev, ""]);
  };

  const updateReferenceUrl = (index: number, value: string) => {
    setReferenceUrls(prev => prev.map((url, i) => i === index ? value : url));
  };

  const removeReferenceUrl = (index: number) => {
    setReferenceUrls(prev => prev.filter((_, i) => i !== index));
  };

  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8 bg-white min-h-screen">
      <Card className="shadow-sm border-border">
        <CardContent className="p-8">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold" data-testid="text-page-title">Create New Course</h1>
            <Button variant="ghost" size="icon" onClick={() => setLocation("/")} data-testid="button-close">
              <X className="h-5 w-5" />
            </Button>
          </div>

          <Tabs value={creationMode} onValueChange={(value) => setCreationMode(value as "ai" | "upload")} className="space-y-6">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="ai">Generate with AI</TabsTrigger>
              <TabsTrigger value="upload">Upload File</TabsTrigger>
            </TabsList>

            <TabsContent value="ai">
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  <FormField
                    control={form.control}
                    name="topic"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Course Topic/Subject *</FormLabel>
                        <FormControl>
                          <Input
                            placeholder="e.g., Introduction to Machine Learning"
                            {...field}
                            data-testid="input-topic"
                          />
                        </FormControl>
                        <FormDescription>
                          What is the main subject of your course?
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="targetAudience"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Target Audience *</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="e.g., Beginners with basic programming knowledge, professionals looking to transition into data science..."
                            rows={3}
                            {...field}
                            data-testid="textarea-audience"
                          />
                        </FormControl>
                        <FormDescription>
                          Who is this course designed for? Include skill level and background.
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="learningObjectives"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Learning Objectives *</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="By the end of this course, students will be able to:&#10;- Understand basic concepts&#10;- Apply the process in practical work&#10;- Evaluate outcomes in realistic scenarios"
                            rows={4}
                            {...field}
                            data-testid="textarea-objectives"
                          />
                        </FormControl>
                        <FormDescription>
                          What specific skills or knowledge will students gain?
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <div>
                    <Label>Reference Website URLs</Label>
                    <div className="mt-3 space-y-3">
                      {referenceUrls.map((url, index) => (
                        <div key={index} className="flex gap-2">
                          <Input
                            type="url"
                            placeholder="https://example.com/resource"
                            value={url}
                            onChange={(e) => updateReferenceUrl(index, e.target.value)}
                            data-testid={`input-url-${index}`}
                          />
                          {referenceUrls.length > 1 && (
                            <Button
                              type="button"
                              variant="outline"
                              size="icon"
                              onClick={() => removeReferenceUrl(index)}
                              data-testid={`button-remove-url-${index}`}
                            >
                              <X className="h-4 w-4" />
                            </Button>
                          )}
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="ghost"
                        onClick={addReferenceUrl}
                        className="text-primary hover:text-blue-600 text-sm font-medium"
                        data-testid="button-add-url"
                      >
                        <Plus className="mr-1 h-4 w-4" />
                        Add Another URL
                      </Button>
                    </div>
                  </div>

                  <div className="border-t border-border pt-6">
                    <Button
                      type="button"
                      variant="ghost"
                      onClick={() => setShowAdvanced(!showAdvanced)}
                      className="flex items-center text-sm font-medium text-muted-foreground hover:text-foreground mb-4"
                      data-testid="button-toggle-advanced"
                    >
                      <ChevronRight className={`mr-2 h-4 w-4 transition-transform ${showAdvanced ? 'rotate-90' : ''}`} />
                      Advanced Options
                    </Button>

                    {showAdvanced && (
                      <div className="space-y-4" data-testid="section-advanced-options">
                        <div className="grid md:grid-cols-2 gap-4">
                          <FormField
                            control={form.control}
                            name="duration"
                            render={({ field }) => (
                              <FormItem>
                                <FormLabel>Course Duration</FormLabel>
                                <Select onValueChange={field.onChange} defaultValue={field.value || undefined}>
                                  <FormControl>
                                    <SelectTrigger data-testid="select-duration">
                                      <SelectValue placeholder="Select duration" />
                                    </SelectTrigger>
                                  </FormControl>
                                  <SelectContent>
                                    <SelectItem value="1-2 hours">1-2 hours</SelectItem>
                                    <SelectItem value="3-5 hours">3-5 hours</SelectItem>
                                    <SelectItem value="6-10 hours">6-10 hours</SelectItem>
                                    <SelectItem value="10+ hours">10+ hours</SelectItem>
                                  </SelectContent>
                                </Select>
                                <FormMessage />
                              </FormItem>
                            )}
                          />

                          <FormField
                            control={form.control}
                            name="difficulty"
                            render={({ field }) => (
                              <FormItem>
                                <FormLabel>Difficulty Level</FormLabel>
                                <Select onValueChange={field.onChange} defaultValue={field.value || undefined}>
                                  <FormControl>
                                    <SelectTrigger data-testid="select-difficulty">
                                      <SelectValue placeholder="Select difficulty" />
                                    </SelectTrigger>
                                  </FormControl>
                                  <SelectContent>
                                    <SelectItem value="Beginner">Beginner</SelectItem>
                                    <SelectItem value="Intermediate">Intermediate</SelectItem>
                                    <SelectItem value="Advanced">Advanced</SelectItem>
                                    <SelectItem value="Expert">Expert</SelectItem>
                                  </SelectContent>
                                </Select>
                                <FormMessage />
                              </FormItem>
                            )}
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex justify-between pt-6">
                    <Button
                      type="button"
                      variant="ghost"
                      onClick={() => setLocation("/")}
                      data-testid="button-cancel"
                    >
                      Cancel
                    </Button>
                    <Button
                      type="submit"
                      disabled={createCourseMutation.isPending}
                      data-testid="button-generate-outline"
                    >
                      {createCourseMutation.isPending ? "Creating..." : "Generate Course Outline"}
                    </Button>
                  </div>
                </form>
              </Form>
            </TabsContent>

            <TabsContent value="upload" className="space-y-6">
              <div>
                <Label>Upload Source Document</Label>
                <div className="mt-3 border-2 border-dashed border-border rounded-lg p-8 text-center hover:border-primary transition-colors cursor-pointer">
                  <input
                    type="file"
                    className="hidden"
                    multiple
                    accept=".pdf,.txt,.doc,.docx,.ppt,.pptx"
                    onChange={handleFileSelect}
                    id="file-upload"
                    data-testid="input-file-upload"
                  />
                  <label htmlFor="file-upload" className="cursor-pointer" data-testid="label-file-upload">
                    <CloudUpload className="h-8 w-8 text-muted-foreground mb-2 mx-auto" />
                    <p className="text-sm text-muted-foreground mb-1">Drop files here or click to upload</p>
                    <p className="text-xs text-muted-foreground">PDF, TXT, DOC, DOCX, PPT, PPTX up to 100MB each</p>
                  </label>
                </div>
                <p className="mt-3 text-sm text-muted-foreground">
                  AI will generate the course title, course objective, module learning objectives, and full outline directly from the uploaded document.
                </p>
                {selectedFiles.length > 0 && (
                  <div className="mt-3 space-y-2">
                    {selectedFiles.map((file, index) => (
                      <div key={index} className="flex items-center justify-between text-sm bg-muted rounded p-2" data-testid={`file-${index}`}>
                        <span className="truncate">{file.name}</span>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => removeFile(index)}
                          data-testid={`button-remove-file-${index}`}
                        >
                          <X className="h-3 w-3" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div className="flex justify-between pt-6">
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => setLocation("/")}
                  data-testid="button-cancel-upload"
                >
                  Cancel
                </Button>
                <Button
                  type="button"
                  disabled={createCourseFromUploadMutation.isPending}
                  onClick={() => createCourseFromUploadMutation.mutate()}
                  data-testid="button-generate-outline-from-upload"
                >
                  {createCourseFromUploadMutation.isPending ? "Creating..." : "Create Outline from Upload"}
                </Button>
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </main>
  );
}
